# See: https://github.com/denoland/setup-deno
name: Vite Import Attributes CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        uses: actions/checkout@v6
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      # Check for Code Smells
      - name: Check Formatting
        run: deno fmt --check .
        continue-on-error: true
      - name: Lint Sources
        run: deno lint

      - name: Test
        run: deno task test
